version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: budget_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - budget_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - budget_network
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1

networks:
  budget_network:
    driver: bridge

volumes:
  postgres_data: